import { useEffect, useState } from 'react'
import api, { errMsg } from '../api/client'
import { Button, Card, ErrorNote, Input, Select, Table } from '../components/ui.jsx'

const today = () => new Date().toISOString().slice(0, 10)
const monthAgo = () => new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10)

/** FR-06 / UC-11, UC-12 - PDF/CSV report export with filters. */
export default function Reports() {
  const [form, setForm] = useState({
    type: 'SALES', format: 'PDF', from: monthAgo(), to: today(), category: '', menuItemId: '',
  })
  const [menu, setMenu] = useState([])
  const [history, setHistory] = useState([])
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  const load = async () => {
    const [h, m] = await Promise.all([api.get('/reports/history'), api.get('/menu')])
    setHistory(h.data)
    setMenu(m.data)
  }

  useEffect(() => {
    load().catch((e) => setError(errMsg(e)))
  }, [])

  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }))

  const exportReport = async () => {
    setError('')
    setBusy(true)
    try {
      const params = {
        type: form.type, format: form.format, from: form.from, to: form.to,
        ...(form.category && { category: form.category }),
        ...(form.menuItemId && { menuItemId: form.menuItemId }),
      }
      const { data, headers } = await api.get('/reports/export', { params, responseType: 'blob' })
      const filename = headers['content-disposition']?.match(/filename=(.+)/)?.[1]
        ?? `report.${form.format.toLowerCase()}`
      const url = URL.createObjectURL(data)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      a.click()
      URL.revokeObjectURL(url)
      await load()
    } catch (e) {
      setError(errMsg(e))
    } finally {
      setBusy(false)
    }
  }

  const categories = [...new Set(menu.map((m) => m.category))]

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">Reports</h1>
      <ErrorNote message={error} />

      <Card title="Generate Report">
        <div className="grid gap-3 md:grid-cols-3">
          <Select label="Type" value={form.type} onChange={(e) => set('type', e.target.value)}>
            <option value="SALES">Sales</option>
            <option value="INVENTORY">Inventory</option>
            <option value="PROFIT_LOSS">Profit / Loss</option>
          </Select>
          <Select label="Format" value={form.format} onChange={(e) => set('format', e.target.value)}>
            <option value="PDF">PDF</option>
            <option value="CSV">CSV</option>
          </Select>
          <div />
          <Input label="From" type="date" value={form.from} onChange={(e) => set('from', e.target.value)} />
          <Input label="To" type="date" value={form.to} onChange={(e) => set('to', e.target.value)} />
          <div />
          <Select label="Category filter (optional)" value={form.category}
                  onChange={(e) => set('category', e.target.value)}>
            <option value="">All categories</option>
            {categories.map((c) => <option key={c} value={c}>{c}</option>)}
          </Select>
          {form.type !== 'INVENTORY' && (
            <Select label="Menu item filter (optional)" value={form.menuItemId}
                    onChange={(e) => set('menuItemId', e.target.value)}>
              <option value="">All items</option>
              {menu.map((m) => <option key={m.menuItemId} value={m.menuItemId}>{m.name}</option>)}
            </Select>
          )}
        </div>
        <Button onClick={exportReport} disabled={busy} className="mt-4">
          {busy ? 'Generating…' : `Export ${form.format}`}
        </Button>
      </Card>

      <Card title="Report History">
        <Table headers={['Type', 'Format', 'Period', 'Generated By', 'Generated At']}>
          {history.map((r) => (
            <tr key={r.reportId}>
              <td className="py-2 pr-4">{r.type}</td>
              <td className="py-2 pr-4">{r.format}</td>
              <td className="py-2 pr-4">{r.startDate} → {r.endDate}</td>
              <td className="py-2 pr-4">{r.generatedBy.name}</td>
              <td className="py-2 pr-4 text-slate-500">{new Date(r.generatedAt).toLocaleString()}</td>
            </tr>
          ))}
        </Table>
        {history.length === 0 && <p className="py-4 text-sm text-slate-400">No reports generated yet.</p>}
      </Card>
    </div>
  )
}
